// user register action types
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_FAIL = "USER_REGISETR_FAIL";
//user login action types
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_CONFIRM_SUCCESS = "USER_CONFIRM_SUCCESS";
export const USER_CONFIRM_LOADING = "USER_CONFIRM_LOADING";
export const USER_CONFIRM_FAIL = "USER_CONFIRM_FAIL";

//error message
export const GET_MESSAGE = "GET_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const API_MESSAGE = "API_MESSAGE";
